const adjectives = [
  "Able", "Active", "Brave", "Calm", "Chic", "Cool", "Cute", "Daring", "Eager", "Fair",
  "Fancy", "Fit", "Glad", "Good", "Happy", "Honest", "Jolly", "Kind", "Loyal", "Meek",
  "Nice", "Proud", "Quick", "Quiet", "Rare", "Rich", "Shy", "Silly", "Smart", "Strong",
  "Sweet", "Tall", "Tame", "Tiny", "Vast", "Warm", "Witty", "Young", "Zany", "Bold",
  "Calm", "Bright", "Brisk", "Chill", "Clean", "Clear", "Dandy", "Dazed", "Deft", "Dense",
  "Elfin", "Famed", "Fair", "Firm", "Flash", "Fresh", "Full", "Grand", "Green", "Hard",
  "Huge", "Ideal", "Jazzy", "Jolly", "Juicy", "Keen", "Lush", "Mild", "Muted", "Neat",
  "New", "Odd", "Pale", "Pithy", "Plump", "Posh", "Prime", "Proud", "Quick", "Rich",
  "Robust", "Sassy", "Shiny", "Sleek", "Slim", "Smart", "Snug", "Soft", "Solid", "Spare",
  "Spry", "Stark", "Stout", "Sunny", "Swift", "Tame", "Tasty", "Tidy", "Trendy", "True",
  "Upbeat", "Vivid", "Witty", "Wise", "Wry", "Zesty", "Able", "Agile", "Apt", "Artful",
  "Brisk", "Brave", "Breezy", "Bright", "Busy", "Calm", "Chaste", "Chic", "Chill", "Clear",
  "Clever", "Coy", "Crisp", "Cute", "Daring", "Dazed", "Deft", "Delight", "Droll", "Eager",
  "Elfin", "Elite", "Epic", "Famed", "Fancy", "Fierce", "Fit", "Foxy", "Free", "Fresh",
  "Full", "Glad", "Grand", "Grim", "Gritty", "Hardy", "Hearty", "Heroic", "Ideal", "Jolly",
  "Juicy", "Keen", "Lithe", "Loyal", "Lush", "Meek", "Mellow", "Mild", "Modest", "Neat",
  "Nifty", "Nimble", "Plush", "Posh", "Prime", "Proud", "Quick", "Rich", "Robust", "Sassy",
  "Shiny", "Sleek", "Slim", "Smart", "Snug", "Soft", "Solid", "Spry", "Stark", "Stout",
  "Sunny", "Swift", "Tame", "Tasty", "Tidy", "Trendy", "True", "Upbeat", "Vivid", "Witty",
  "Wise", "Wry", "Zesty", "Active", "Adroit", "Aglow", "Alert", "Alive", "Amused", "Apt",
  "Artful", "Avid", "Brave", "Bright", "Busy", "Calm", "Chill", "Clever", "Coy", "Crisp",
  "Cute", "Daring", "Dazed", "Deft", "Droll", "Eager", "Elfin", "Elite", "Famed", "Fancy",
  "Fit", "Free", "Fresh", "Full", "Glad", "Grand", "Hardy", "Hearty", "Heroic", "Ideal",
  "Jolly", "Juicy", "Keen", "Lithe", "Loyal", "Lush", "Mild", "Modest", "Neat", "Nifty",
  "Nimble", "Plush", "Posh", "Prime", "Proud", "Quick", "Rich", "Robust", "Sassy", "Shiny",
  "Sleek", "Slim", "Smart", "Snug", "Soft", "Solid", "Spry", "Stark", "Stout", "Sunny",
  "Swift", "Tame", "Tasty", "Tidy", "Trendy", "True", "Upbeat", "Vivid", "Witty", "Wise",
  "Wry", "Zesty", "Agile", "Alert", "Alive", "Apt", "Brisk", "Brave", "Breezy", "Busy",
  "Calm", "Chaste", "Chill", "Clear", "Clever", "Coy", "Crisp", "Cute", "Daring", "Dazed",
  "Deft", "Delight", "Droll", "Eager", "Elfin", "Elite", "Epic", "Famed", "Fancy", "Fierce",
  "Fit", "Foxy", "Free", "Fresh", "Full", "Glad", "Grand", "Grim", "Gritty", "Hardy",
  "Hearty", "Heroic", "Ideal", "Jolly", "Juicy", "Keen", "Lithe", "Loyal", "Lush", "Meek",
  "Mellow", "Mild", "Modest", "Neat", "Nifty", "Nimble", "Plush", "Posh", "Prime", "Proud",
  "Quick", "Rich", "Robust", "Sassy", "Shiny", "Sleek", "Slim", "Smart", "Snug", "Soft",
  "Solid", "Spry", "Stark", "Stout", "Sunny", "Swift", "Tame", "Tasty", "Tidy", "Trendy",
  "True", "Upbeat", "Vivid", "Witty", "Wise", "Wry", "Zesty", "Able", "Active", "Brave",
  "Calm", "Chic", "Cool", "Cute", "Daring", "Eager", "Fair", "Fancy", "Fit", "Glad", "Good",
  "Happy", "Honest", "Jolly", "Kind", "Loyal", "Meek", "Nice", "Proud", "Quick", "Quiet",
  "Rare", "Rich", "Shy", "Silly", "Smart", "Strong", "Sweet", "Tall", "Tame", "Tiny", "Vast",
  "Warm", "Witty", "Young", "Zany", "Bold", "Calm", "Bright", "Brisk", "Chill", "Clean",
  "Clear", "Dandy", "Dazed", "Deft", "Dense", "Elfin", "Famed", "Fair", "Firm", "Flash",
  "Fresh", "Full", "Grand", "Green", "Hard", "Huge", "Ideal", "Jazzy", "Jolly", "Juicy",
  "Keen", "Lush", "Mild", "Muted", "Neat", "New", "Odd", "Pale", "Pithy", "Plump", "Posh",
  "Prime", "Proud", "Quick", "Rich", "Robust", "Sassy", "Shiny", "Sleek", "Slim", "Smart",
  "Snug", "Soft", "Solid", "Spare", "Spry", "Stark", "Stout", "Sunny", "Swift", "Tame",
  "Tasty", "Tidy", "Trendy", "True", "Upbeat", "Vivid", "Witty", "Wise", "Wry", "Zesty"
]

export const randomAdjective = () => adjectives[Math.floor(Math.random() * adjectives.length)];